import type { Metadata } from 'next'
import './globals.css'

import clsx from 'clsx'
import localFont from 'next/font/local'

const EduTASBeginner = localFont({
  src: '../utils/assets/fonts/Edu_TAS_Beginner/EduTASBeginner-VariableFont_wght.ttf',
  display: 'swap',
})

const Agbalumo = localFont({
  src: '../utils/assets/fonts/Agbalumo/Agbalumo-Regular.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={EduTASBeginner.className}>
        <header className="max-w-6xl mx-auto p-4"> <span className={clsx(Agbalumo.className, "text-2xl")}>Samyar</span></header>

        {children}

      </body>
    </html>
  )
}
